# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
development:
  adapter: postgresql
  encoding: unicode
  database: filey_development
  pool: 5
  username: jirka
  password:
test:
  adapter: postgresql
  encoding: unicode
  database: filey_test
  pool: 5
  username: jirka
  password:
production:
  adapter: postgresql
  encoding: unicode
  database: filey_production
  pool: 5
  username: jirka
  password:
